create table LEBEDEV_EG.hospital_2 (
    id_hospital number generated by default as identity (start with 1 maxvalue 999999 minvalue 1 nocache nocycle noorder) primary key,
    name_hospital varchar(100) unique not null,
    is_open number(1,0) not null,
    deleted date null
);

create table LEBEDEV_EG.SPECIALITY_2 (
    id_speciality number generated by default as identity
        (start with 1 maxvalue 999999 minvalue 1 nocycle nocache noorder) primary key,
    name_speciality varchar(100) not null,
    --age_group number references LEBEDEV_EG.AGE_GROUP(id_age_group) not null,
    --sex number references LEBEDEV_EG.sex(id_sex) not null,
    deleted date null
);

create table LEBEDEV_EG.doctor_2 (
    id_doctor number generated by default as identity
        (start with 1 maxvalue 999999 minvalue 1 nocycle nocache noorder) primary key,
--     id_hospital number references LEBEDEV_EG.hospital(id_hospital) not null,
    area number not null,
    qualification varchar(100) not null,
    deleted date null
);

create table LEBEDEV_EG.hospital_speciality_doctor_relation(
    "ROW" number generated by default as identity (start with 1 maxvalue 999999 minvalue 1 nocache nocycle noorder) primary key,
    id_hospital number references LEBEDEV_EG.hospital_2(id_hospital) not null,
    id_speciality number references LEBEDEV_EG.SPECIALITY_2(id_speciality) not null,
    id_doctor number references LEBEDEV_EG.doctor_2(id_doctor) not null
);