create table LEBEDEV_EG.REGION (
    id_region number generated by default as identity
        (start with 1 maxvalue 999999 minvalue 1 nocache nocycle noorder) primary key,
    name_region varchar(100) unique not null
);

create table LEBEDEV_EG.city (
    id_city number generated by default as identity
        (start with 1 maxvalue 999999 minvalue 1 nocycle nocache noorder) primary key,
    city_name varchar(100) unique not null ,
    id_region number references LEBEDEV_EG.REGION(id_region) not null
);

create table LEBEDEV_EG.Medical_organization (
    id_medical_organization number generated by default as identity
        (start with 1 maxvalue 999999 minvalue 1 nocache nocycle noorder) primary key,
    name_medical_organization varchar(100) unique not null
);

create table LEBEDEV_EG.city_medical_organization (
    id_city number references LEBEDEV_EG.CITY(id_city),
    id_medical_organization number references LEBEDEV_EG.MEDICAL_ORGANIZATION(ID_MEDICAL_ORGANIZATION),
    primary key (id_city,id_medical_organization)
)
