insert into LEBEDEV_EG.DOCUMENT(NAME_DOCUMENT)
values ('Паспорт');
insert into PATIENT (SURNAME, NAME, PATRONYMIC, SEX, PHONE, AREA)
values ('123','123','123',1,2131,1);
insert into LEBEDEV_EG.PATIENT_DOCUMENT (ID_PATIENT, ID_DOCUMENT)
values (1,2);

select P.NAME, D.NAME_DOCUMENT from PATIENT_DOCUMENT
inner join PATIENT P on PATIENT_DOCUMENT.ID_PATIENT = P.ID_PATIENT
inner join DOCUMENT D on D.ID_DOCUMENT = PATIENT_DOCUMENT.ID_DOCUMENT